#
# https://github.com/P3TERX/IBM-CF-V2
#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: IBM Cloud Foundry - Caddy

env:
  IBM_CF_API: https://api.us-south.cf.cloud.ibm.com
  IBM_CF_APP_MEM: 128M
  IGNOREIMAGE: false

on:
  push:
    paths:
      - 'v2ray/*'
  workflow_dispatch:
  schedule:
    - cron: 25 20 1/7 * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IBM_CF_USERNAME: ${{ secrets.IBM_CF_USERNAME2 }}
      IBM_CF_PASSWORD: ${{ secrets.IBM_CF_PASSWORD }}
      IBM_CF_ORG_NAME: ${{ secrets.IBM_CF_ORG_NAME }}
      IBM_CF_SPACE_NAME: ${{ secrets.IBM_CF_SPACE_NAME }}
      IBM_CF_APP_NAME: ${{ secrets.IBM_CF_APP_NAME2 }}
      V2_UUID: ${{ secrets.V2_UUID }}
      V2_WS_PATH_VLESS: ${{ secrets.V2_WS_PATH }}
      V2RAY_IMAGE_NAME: ${{ secrets.V2RAY_IMAGE_NAME }}
      TROJAN_WS_PATH: ${{ secrets.TROJAN_WS_PATH }}
      TROJAN_PWD: ${{ secrets.TROJAN_PWD }}
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Cloud Foundry CLI
      run: |
        curl -fsSL "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zxC /tmp
        sudo install -m 755 /tmp/cf7 /usr/local/bin/cf
        cf version
    - name: Login to IBM Cloud Foundry
      run: |
        cf login \
          -a "${IBM_CF_API}" \
          -u "${IBM_CF_USERNAME}" \
          -p "${IBM_CF_PASSWORD}" \
          -o "${IBM_CF_ORG_NAME:-$IBM_CF_USERNAME}" \
          -s "${IBM_CF_SPACE_NAME:-dev}"
           
    - name: Modify File
      if: env.IGNOREIMAGE != 'true'
      working-directory: v2ray
      run: |
          sed -i "s@V2RAYUUID@${V2_UUID}@g" Dockerfile
          sed -i "s@V2RAYWSPATH@${V2_WS_PATH_VLESS}@g" Dockerfile   
          sed -i "s@TROJANWSPATH@${TROJAN_WS_PATH}@g" Dockerfile
          sed -i "s@TROJANPWD@${TROJAN_PWD}@g" Dockerfile
#          sed -i "s@ENV CADDY=true@ENV CADDY=false@g" Dockerfile   
          
    - name: Build and publish image
      if: env.IGNOREIMAGE != 'true'
      uses: ilteoood/docker_buildx@master        
      with:
          publish: true
          imageName: ${{ secrets.V2RAY_IMAGE_NAME }}
          dockerFile: v2ray/Dockerfile
          context: v2ray
          platform: linux/amd64
          dockerUser:  ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}   
 
    - name: Sleep for 1 minutes
      if: env.IGNOREIMAGE != 'true'
      uses: jakejarvis/wait-action@master
      with:
        time: '1m'

    - name: Generate Manifest File
      run: |
        cat << P3TERX > manifest.yml
        applications:
        - name: ${IBM_CF_APP_NAME}
          memory: ${IBM_CF_APP_MEM}
          random-route: true
          docker:
            image: ${V2RAY_IMAGE_NAME}
        P3TERX
        
    - name: Deploy Cloud Foundry App
      run: cf push
